print('{:=^51}'.format(' Exercício 007 '))
nome = str(input('Nome: '))
n1 = float(input('1ª nota: '))
n2 = float(input('2ª nota: '))
print('\033[31m{} ficou com média {:.1f}\033[m'.format(nome, (n1+n2)/2))
