print('{:=^51}'.format(' Exercício 004 '))
a = input('Digite algo: ')
print('Seu tipo primitivo é: ', type(a))
print('Só contém espaço? ', a.isspace())
print('É alfanumérico? ', a.isalnum())
print('É numérico? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É maiúsculo? ', a.isupper())
print('É minúsculo? ', a.islower())
print('Está capitulada? ', a.istitle())
